s1=input("nhap chuoi s1:")
s2=input("nhap chuoi s2:")
s3=input("nhap chuoi s3:")
a=int(input("nhap diem dau:"))
b=int(input("nhap diem cuoi:"))
print("chieu dai cua chuoi s1 la :",len(s1))
print("chieu dai cua chuoi s2 la :",len(s2))
print("chieu dai cua chuoi s3 la :",len(s3))
print("chuoi s4 =",s1[a:b])
print("chui s2 lap lai 2 lan =",s2*a)